import type { Domain, Stats } from '../types';

export const mockStats: Stats = {
  totalDomains: 17,
  indexedUrls: 1450, // Placeholder
  warnings: 2, // Auto-Renew & Transferred might be flagged
  errors: 0,
};

export const mockDomains: Domain[] = [
  {
    id: '1',
    name: 'teqh.com',
    url: 'https://teqh.com',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:teqh.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://teqh.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=teqh.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '2',
    name: 'refundschedule.com',
    url: 'https://refundschedule.com',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:refundschedule.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://refundschedule.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=refundschedule.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '3',
    name: 'refundstatus.com',
    url: 'https://refundstatus.com',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:refundstatus.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://refundstatus.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=refundstatus.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '4',
    name: 'refundcalculator.com',
    url: 'https://refundcalculator.com',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:refundcalculator.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://refundcalculator.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=refundcalculator.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '5',
    name: 'hotspringscpa.com',
    url: 'https://hotspringscpa.com',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:hotspringscpa.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://hotspringscpa.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=hotspringscpa.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '6',
    name: 'andrewpennington.cpa',
    url: 'https://andrewpennington.cpa',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:andrewpennington.cpa',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://andrewpennington.cpa',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=andrewpennington.cpa',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '7',
    name: 'incometaxforums.com',
    url: 'https://incometaxforums.com',
    status: 'warning',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:incometaxforums.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://incometaxforums.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=incometaxforums.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '8',
    name: 'irstaxrefundschedule.com',
    url: 'https://irstaxrefundschedule.com',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:irstaxrefundschedule.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://irstaxrefundschedule.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=irstaxrefundschedule.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '9',
    name: 'irstaxseason.com',
    url: 'https://irstaxseason.com',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:irstaxseason.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://irstaxseason.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=irstaxseason.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '10',
    name: 'irschat.com',
    url: 'https://irschat.com',
    status: 'warning',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:irschat.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://irschat.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=irschat.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'pending' },
  },
  {
    id: '11',
    name: 'irsscams.com',
    url: 'https://irsscams.com',
    status: 'warning',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:irsscams.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://irsscams.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=irsscams.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'pending' },
  },
  {
    id: '12',
    name: 'freetaxweekend.com',
    url: 'https://freetaxweekend.com',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:freetaxweekend.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://freetaxweekend.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=freetaxweekend.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '13',
    name: 'compoundcommander.com',
    url: 'https://compoundcommander.com',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:compoundcommander.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://compoundcommander.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=compoundcommander.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '14',
    name: 'compoundtycoon.com',
    url: 'https://compoundtycoon.com',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:compoundtycoon.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://compoundtycoon.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=compoundtycoon.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '15',
    name: 'minmaxmuscle.com',
    url: 'https://minmaxmuscle.com',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:minmaxmuscle.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://minmaxmuscle.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=minmaxmuscle.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '16',
    name: 'codmobile.org',
    url: 'https://codmobile.org',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:codmobile.org',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://codmobile.org',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=codmobile.org',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
  {
    id: '17',
    name: 'woodworkslab.com',
    url: 'https://woodworkslab.com',
    status: 'active',
    gscLink: 'https://search.google.com/search-console?resource_id=sc-domain:woodworkslab.com',
    bingLink: 'https://www.bing.com/webmasters/home?siteUrl=https://woodworkslab.com',
    yandexLink: 'https://webmaster.yandex.com/siteinfo/?host=woodworkslab.com',
    indexNowKey: 'TeqhIndexNowKey2026',
    engines: {
      google: { indexed: true, lastChecked: '2026-02-22T10:00:00Z', rank: 1, issues: [] },
      bing: { indexed: true, lastChecked: '2026-02-22T10:05:00Z', rank: 1, issues: [] },
      yandex: { indexed: true, lastChecked: '2026-02-22T14:30:00Z', rank: 1, issues: [] },
    },
    indexNow: { lastPush: '2026-02-22T09:00:00Z', status: 'success' },
  },
];
